VarContext.customJV := VarContext.JavaVersionToSetting.value

VarContext.changeDeptVar                   := "commons-lang3"
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.20.0"

VarContext.changeDeptVar                   := "commons-compress"
libraryDependencies += "org.apache.commons" % "commons-compress" % "1.28.0"

VarContext.changeDeptVar          := "jsoup"
libraryDependencies += "org.jsoup" % "jsoup" % "1.22.1"

VarContext.changeDeptVar              := "jintellitype"
libraryDependencies += "com.melloware" % "jintellitype" % "1.5.6"

VarContext.changeDeptVar               := "logback-classic"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.5.25"

VarContext.changeDeptVar                  := "javet"
libraryDependencies += "com.caoccao.javet" % "javet"                          % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-linux-arm64"
libraryDependencies += "com.caoccao.javet" % "javet-node-linux-arm64"         % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-linux-arm64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-linux-arm64-i18n"    % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-linux-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-node-linux-x86_64"        % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-linux-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-linux-x86_64-i18n"   % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-macos-arm64"
libraryDependencies += "com.caoccao.javet" % "javet-node-macos-arm64"         % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-macos-arm64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-macos-arm64-i18n"    % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-macos-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-node-macos-x86_64"        % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-macos-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-macos-x86_64-i18n"   % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-windows-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-node-windows-x86_64"      % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-windows-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-windows-x86_64-i18n" % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-android"
libraryDependencies += "com.caoccao.javet" % "javet-node-android"             % "5.0.3"
VarContext.changeDeptVar                  := "javet-node-android-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-node-android-i18n"        % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-linux-arm64"
libraryDependencies += "com.caoccao.javet" % "javet-v8-linux-arm64"           % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-linux-arm64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-linux-arm64-i18n"      % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-linux-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-v8-linux-x86_64"          % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-linux-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-linux-x86_64-i18n"     % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-macos-arm64"
libraryDependencies += "com.caoccao.javet" % "javet-v8-macos-arm64"           % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-macos-arm64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-macos-arm64-i18n"      % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-macos-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-v8-macos-x86_64"          % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-macos-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-macos-x86_64-i18n"     % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-windows-x86_64"
libraryDependencies += "com.caoccao.javet" % "javet-v8-windows-x86_64"        % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-windows-x86_64-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-windows-x86_64-i18n"   % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-android"
libraryDependencies += "com.caoccao.javet" % "javet-v8-android"               % "5.0.3"
VarContext.changeDeptVar                  := "javet-v8-android-i18n"
libraryDependencies += "com.caoccao.javet" % "javet-v8-android-i18n"          % "5.0.3"

VarContext.changeDeptVar                 := "jnativehook"
libraryDependencies += "com.github.kwhat" % "jnativehook" % "2.2.2"

VarContext.changeDeptVar                   := "commons-io"
libraryDependencies += "org.apache.commons" % "commons-io" % "1.3.2"

VarContext.changeDeptVar          := "slf4j-simple"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "2.0.17"

VarContext.changeDeptVar          := "slf4j-nop"
libraryDependencies += "org.slf4j" % "slf4j-nop" % "2.0.17"

VarContext.changeDeptVar               := "h2"
libraryDependencies += "com.h2database" % "h2" % "2.4.240"

VarContext.changeDeptVar                   := "commons-math3"
libraryDependencies += "org.apache.commons" % "commons-math3" % "3.6.1"

VarContext.changeDeptVar             := "typesafe-config"
libraryDependencies += "com.typesafe" % "config" % "1.4.5"

VarContext.changeDeptVar             := "javacv-platform"
libraryDependencies += "org.bytedeco" % "javacv-platform" % "1.5.12"

VarContext.changeDeptVar          := "mysql-connector-java"
libraryDependencies += "com.mysql" % "mysql-connector-j" % "9.5.0"

VarContext.changeDeptVar               := "postgresql-jdbc"
libraryDependencies += "org.postgresql" % "postgresql" % "42.7.8"

VarContext.changeDeptVar                := "jmh-generator-annprocess"
libraryDependencies += "org.openjdk.jmh" % "jmh-generator-annprocess" % "1.37"

VarContext.changeDeptVar              := "sbt-launch"
libraryDependencies += "org.scala-sbt" % "sbt-launch" % "1.12.0"
